
apiVersion: v1
kind: Service
metadata:
  name: book-api
  namespace: bookwish
spec:
  selector:
    app: book-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
