
apiVersion: v1
kind: Service
metadata:
  name: book-frontend
  namespace: bookwish
spec:
  selector:
    app: book-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
